export let mockEvents = { events_date: '2014-12-25T00:00:00-05:00',
    event:
    [ { event_id: '20141225-washington-wizards-at-new-york-knicks',
        event_status: 'completed',
        sport: 'NBA',
        start_date_time: '2014-12-25T12:00:00-05:00',
        season_type: 'regular',
        away_team: [Object],
        home_team: [Object],
        site: [Object],
        away_period_scores: [Object],
        home_period_scores: [Object],
        away_points_scored: 102,
        home_points_scored: 91 },
        { event_id: '20141225-oklahoma-city-thunder-at-san-antonio-spurs',
            event_status: 'completed',
            sport: 'NBA',
            start_date_time: '2014-12-25T14:30:00-05:00',
            season_type: 'regular',
            away_team: [Object],
            home_team: [Object],
            site: [Object],
            away_period_scores: [Object],
            home_period_scores: [Object],
            away_points_scored: 114,
            home_points_scored: 106 },
        { event_id: '20141225-cleveland-cavaliers-at-miami-heat',
            event_status: 'completed',
            sport: 'NBA',
            start_date_time: '2014-12-25T17:00:00-05:00',
            season_type: 'regular',
            away_team: [Object],
            home_team: [Object],
            site: [Object],
            away_period_scores: [Object],
            home_period_scores: [Object],
            away_points_scored: 91,
            home_points_scored: 101 },
        { event_id: '20141225-los-angeles-lakers-at-chicago-bulls',
            event_status: 'completed',
            sport: 'NBA',
            start_date_time: '2014-12-25T20:00:00-05:00',
            season_type: 'regular',
            away_team: [Object],
            home_team: [Object],
            site: [Object],
            away_period_scores: [Object],
            home_period_scores: [Object],
            away_points_scored: 93,
            home_points_scored: 113 },
        { event_id: '20141225-golden-state-warriors-at-los-angeles-clippers',
            event_status: 'completed',
            sport: 'NBA',
            start_date_time: '2014-12-25T22:30:00-05:00',
            season_type: 'regular',
            away_team: [Object],
            home_team: [Object],
            site: [Object],
            away_period_scores: [Object],
            home_period_scores: [Object],
            away_points_scored: 86,
            home_points_scored: 100
        }
    ]
};